github.com:
    oauth_token: ghs_4486636_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRobmQiLCJjdHgiOiJqY2dhM2V2RlVwdk95aDM0TnE0UzBPSVZYTEZhbWlvNVJKWW5mUW1HTHdRRkx0Y3VlZlpWUUFNRzZBIiwiZXhwIjoxNzg3NTA1NzMxLCJpYXQiOjE3ODc1MDIxMzEsImlzcyI6ImdpdGh1YiIsImp0aSI6ImYxMjdkODVjLTFmMjMtNGY3NS04MTczLWU1ZWY5MDc5YmEyZCIsInZlciI6M30.ZesmjmERkaP2BAikhDkWaE557dRndpZPZkUw7uEEyYj8Vpq62w7BmP9CIAKGTK91F47kcUbe7YmWQSHVThM3eA
    user: x-access-token
    git_protocol: https
