github.com:
    oauth_token: ghs_4486636_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRobmQiLCJjdHgiOiI1QjgyNXZWYWRCdUpvcU5yTXd0UDRRNWZGSzVCU2M1bWxIenRYZ3BUQnpfSlBhRzZPQWhUOFh3R29nIiwiZXhwIjoxNzg3NTA1NDMxLCJpYXQiOjE3ODc1MDE4MzEsImlzcyI6ImdpdGh1YiIsImp0aSI6IjIyNmQwOWU3LWE1MzgtNDIwZS1iNWNjLTkyOWFkMTE2YzMyYiIsInZlciI6M30.3189rU4e-SuzTnCgTGR6G47mdS_jqcnYncDBNi_JMOPkjs7_k2Z5JIl1zk2RBXo5IjmQ_8XkP9cjvxuj9s3HNQ
    user: x-access-token
    git_protocol: https
